name: escape_from_me
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.5
  simple_logger: ^1.9.0
  flutter_svg: ^1.1.0
  rive: ^0.10.0
  battery_plus: ^2.0.1
  maze: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_flavorizr: ^2.0.0
  flutter_launcher_icons: "^0.11.0"
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.0.3

# assets
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animation/

# flutter pub run build_runner build --delete-conflicting-outputs
flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon_door.png"

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/black_white.png
  color_dark: "#222222"
  image_dark: assets/splash/black_white.png
  fullscreen: true
